### ISSUE TITLE
Don't assume running on a legacy machine with access to existing Lustre

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/hgi-ansible#29]
The offending setting here:
https://github.com/wtsi-hgi/hgi-systems/blob/97a837106145b75d3109ff797481027dab2fcff9/ansible/roles/openstack-image/defaults/main.yml#L23

Causes this when `site-bootstap.yml` is ran on any generic machine:
```
TASK [openstack-image : fetch image from s3] ***********************************************************************************************************************************************************************************************************************************
task path: /data/hgi-systems/ansible/roles/openstack-image/tasks/main.yml:36
skipping: [delta-hgi-docker-image] => {
    "changed": false,
    "skip_reason": "Conditional result was False",
    "skipped": true
}
Using module_utils file /usr/local/lib/python3.5/dist-packages/ansible-2.4.0-py3.5.egg/ansible/module_utils/six/__init__.py
Using module_utils file /usr/local/lib/python3.5/dist-packages/ansible-2.4.0-py3.5.egg/ansible/module_utils/ec2.py
Using module_utils file /usr/local/lib/python3.5/dist-packages/ansible-2.4.0-py3.5.egg/ansible/module_utils/basic.py
Using module_utils file /usr/local/lib/python3.5/dist-packages/ansible-2.4.0-py3.5.egg/ansible/module_utils/six/_six.py
Using module_utils file /usr/local/lib/python3.5/dist-packages/ansible-2.4.0-py3.5.egg/ansible/module_utils/cloud.py
Using module_utils file /usr/local/lib/python3.5/dist-packages/ansible-2.4.0-py3.5.egg/ansible/module_utils/pycompat24.py
Using module_utils file /usr/local/lib/python3.5/dist-packages/ansible-2.4.0-py3.5.egg/ansible/module_utils/_text.py
Using module file /usr/local/lib/python3.5/dist-packages/ansible-2.4.0-py3.5.egg/ansible/modules/cloud/amazon/s3.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1495791045.959745-133230312536533 `" && echo ansible-tmp-1495791045.959745-133230312536533="` echo /root/.ansible/tmp/ansible-tmp-1495791045.959745-133230312536533 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpb43kzb78 TO /root/.ansible/tmp/ansible-tmp-1495791045.959745-133230312536533/s3.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1495791045.959745-133230312536533/ /root/.ansible/tmp/ansible-tmp-1495791045.959745-133230312536533/s3.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1495791045.959745-133230312536533/s3.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1495791045.959745-133230312536533/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/boto/s3/key.py", line 1707, in get_contents_to_filename
    with open(filename, 'wb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/scratch115/teams/hgi/users/mercury/tmp/hgi-docker-xenial-8b5badf9'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_49cubt5l/ansible_module_s3.py", line 792, in <module>
    main()
  File "/tmp/ansible_49cubt5l/ansible_module_s3.py", line 614, in main
    download_s3file(module, s3, bucket, obj, dest, retries, version=version, validate=validate)
  File "/tmp/ansible_49cubt5l/ansible_module_s3.py", line 416, in download_s3file
    key.get_contents_to_filename(dest)
  File "/usr/lib/python3/dist-packages/boto/s3/key.py", line 1714, in get_contents_to_filename
    os.remove(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/scratch115/teams/hgi/users/mercury/tmp/hgi-docker-xenial-8b5badf9'

fatal: [delta-hgi-ci-docker-image -> 127.0.0.1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/boto/s3/key.py\", line 1707, in get_contents_to_filename\n    with open(filename, 'wb') as fp:\nFileNotFoundError: [Errno 2] No such file or directory: '/lustre/scratch115/teams/hgi/users/mercury/tmp/hgi-docker-xenial-8b5badf9'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_49cubt5l/ansible_module_s3.py\", line 792, in <module>\n    main()\n  File \"/tmp/ansible_49cubt5l/ansible_module_s3.py\", line 614, in main\n    download_s3file(module, s3, bucket, obj, dest, retries, version=version, validate=validate)\n  File \"/tmp/ansible_49cubt5l/ansible_module_s3.py\", line 416, in download_s3file\n    key.get_contents_to_filename(dest)\n  File \"/usr/lib/python3/dist-packages/boto/s3/key.py\", line 1714, in get_contents_to_filename\n    os.remove(filename)\nFileNotFoundError: [Errno 2] No such file or directory: '/lustre/scratch115/teams/hgi/users/mercury/tmp/hgi-docker-xenial-8b5badf9'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

**Comment by colin-nolan** [comment]
The added complication to this issue is that the current implementation works with the idea that there is an image cache on the machine running the playbook:
https://github.com/wtsi-hgi/hgi-systems/blob/master/ansible/roles/openstack-image/tasks/main.yml#L30-L34

Given the `openstack_image_delegate` is [currently set to the localhost](https://github.com/wtsi-hgi/hgi-systems/blob/97a837106145b75d3109ff797481027dab2fcff9/ansible/roles/openstack-image/defaults/main.yml#L24), the assumtion is that the machine running the playbook has this cache. I don't think this is a good idea as the playbook should not be coupled to a particular set of exclusive machines (e.g. those on the local network with lustre mounted).

Alternatives would be:
- To move away from the idea of having an image cache and just download from S3 into a temp directory, upload to Glance and then remove the temp (alternatively, stream directly from S3 -> Glance but I'm unsure if this can be done easily in Ansible).
- Setup a machine that is specifically designed to have this task delgated to it (less preferable IMO).

**Comment by jrandall** [comment]
Should be ok now (as of  58658abf ) - this won't run unless it needs to and it will use the value of the environment variable `TMPDIR` if you have it set (so set it).

**Comment by colin-nolan** [comment]
`openstack_image_tmp_dir` should be changed in the future to remove the coupling to the setup of internal machines. However, `TMPDIR` will work for now.
